name: OCI Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Set up QEMU and Docker Buildx for cross-platform builds
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Login to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image for multiple architectures with specific args
      run: |
        docker buildx build \
          --platform linux/amd6 \
          --tag ghcr.io/${{ github.actor }}/terasky-insights:latest \
          --build-arg TARGETVERSION=v0.21.3 \
          --build-arg TARGETARCH=amd64 --output=type=image,push=true . \
          && \
          docker buildx build \
          --platform linux/arm64 \
          --tag ghcr.io/${{ github.actor }}/terasky-insights:latest \
          --build-arg TARGETVERSION=v0.21.3 \
          --build-arg TARGETARCH=arm64 --output=type=image,push=true .
