name: OCI Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Set up QEMU and Docker Buildx for cross-platform builds
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Login to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build and push the Docker image for linux/amd64
    - name: Build and push Docker image for multiple platforms
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.actor }}/terasky-insights:latest
        build-args: |
          TARGETVERSION=v0.21.3
          TARGETARCH=amd64
        platforms: linux/amd64

   # Build and push the Docker image for linux/arm64
    - name: Build and push Docker image for multiple platforms
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.actor }}/terasky-insights:latest
        build-args: |
          TARGETVERSION=v0.21.3
          TARGETARCH=arm64
        platforms: linux/arm64
